name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Build Docker image
        run: docker build -t tme-teste-go1 .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 590184040663.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image
        run: docker tag tme-teste-go1:latest 590184040663.dkr.ecr.us-east-1.amazonaws.com/tme-teste-go1:latest

      - name: Push Docker image to AWS ECR
        run: docker push 590184040663.dkr.ecr.us-east-1.amazonaws.com/tme-teste-go1:latest

